artifacts:
  artifacts_dir: artifacts
  pickle_format_data_dir: pickle_format_data
  img_pickle_file_name: img_pickle_file.pkl
  feature_extraction_directory: extracted_features
  extracted_feature_names: embedding.pkl